@startuml

skinparam monochrome false
skinparam classBackgroundColor White/Beige
skinparam classBorderColor Black
skinparam dpi 300
skinparam componentStyle uml2

class AuthService {
  + login(username: str, pwd: str): User
  + logout(session_id: int): void
}

interface IUserRepository <<interface>> {
  + get_user_by_credentials(username: str, password: str): User | None
  + get_user_by_id(id: int): User
  + update_last_login(id: int): void
}

class FakeUserRepository {
  - _users: dict
  + get_user_by_credentials(username: str, pwd: str): User | None
  + get_user_by_id(id: int): User
}

class PostgresAdapter {
  - _pool: ConnectionPool
  + get_user_by_credentials(username: str, pwd: str): User | None
  + get_user_by_id(id: int): User
  + update_last_login(id: int): void
}

AuthService ..> IUserRepository : <<use>>
FakeUserRepository .up.|> IUserRepository : <<realize>>
PostgresAdapter .up.|> IUserRepository : <<realize>>

@enduml